name: samba

services:
  samba:
    container_name: samba
    restart: unless-stopped
    image: dperson/samba
    environment:
      - USERID=0
      - GROUPID=0
    ports:
      - 445:445/tcp
    command: '-W -s "Share;/share;yes;no;no" -u "${SMB_USER};${SMB_PWD}"'
