name: autoscaler

services:
  autoscaler:
    # image: mgarnier11/autoscaler:${AUTOSCALER_VERSION}
    image: mgarnier11/autoscaler:latest
    restart: unless-stopped
    container_name: autoscaler
    env_file:
      - ./autoscaler.env
    environment:
      RUNNER_IMAGE: mgarnier11/github-runner:latest
      SSH_USER: ${SSH_USER}
      NTFY_SERVER: ${NTFY_SERVER}
      NTFY_TOPIC: ${NTFY_TOPIC}
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
      DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
      DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME}
      DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD}
      RUNTIME: sysbox-runc
    ports:
      - ${APOLLON_AUTOSCALER_PORT}:3000
    labels:
      # traefik-conf.http.routers.autoscaler.rule: Host(`autoscaler.${PUBLIC_DOMAIN_NAME}`)
      # traefik-conf.http.routers.autoscaler.service: apollon_autoscaler
      # traefik-conf.http.routers.autoscaler.entrypoints: https
      # traefik-conf.http.routers.autoscaler.tls.certResolver: tls-resolver
      traefik-conf.port: ${APOLLON_AUTOSCALER_PORT}
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: autoscaler
        target: /config
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:${APOLLON_AUTOSCALER_PORT} || exit 1
      start_period: 10s

volumes:
  docker-data:
    external: true
