name: autoscaler

services:
  autoscaler:
    image: docker.io/mgarnier11/autoscaler:latest
    restart: unless-stopped
    container_name: autoscaler
    environment:
      REGISTRATION_URL: "${REGISTRATION_URL}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      RUNNER_IMAGE: "mgarnier11/runner:arm64"
      DOCKER_REGISTRY_URL: "${DOCKER_REGISTRY_URL}"
      DOCKER_REGISTRY_USERNAME: "${DOCKER_REGISTRY_USERNAME}"
      DOCKER_REGISTRY_PASSWORD: "${DOCKER_REGISTRY_PASSWORD}"
      ARTIFACTORY_TOKEN: "test"
      SCALE_SET_NAME: "zephyr"
      MAX_RUNNERS: "10"
      MIN_RUNNERS: "0"
      LABELS: "linux/arm64"
      RUNNER_GROUP: "default"
      DOCKER_HOSTS: "unix:///var/run/docker.sock"
      RUNTIME: "sysbox-runc"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
