services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:12
    container_name: nfs
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/nfs-share
    volumes:
      - /docker-data:/nfs-share/docker-data
      - /home/mgarnier:/nfs-share/apollon-home
    ports:
      - 2049:2049
