services:
  nfs-server:
    image: erichough/nfs-server
    container_name: nfs-server
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    environment:
      - NFS_EXPORT_0=/nfs-share *(rw,sync,no_subtree_check)
    volumes:
      - /hdd-1:/nfs-share/hdd-1
      - /hdd-2:/nfs-share/hdd-2
      - /hdd-3:/nfs-share/hdd-3
      - /ssd-1:/nfs-share/ssd-1
      - /home/mgarnier:/nfs-share/athena-home
      - /big-hdd:/nfs-share/big-hdd
      - /ssd-1/docker-data:/nfs-share/docker-data
    ports:
      - "2049:2049"
