services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:11-arm
    container_name: nfs
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data/nfs-share
    volumes:
      # - /docker-data:/data/nfs-share/docker-data
      - /home/mgarnier:/data/nfs-share/zephyr-home
    ports:
      - 2049:2049
