name: bitwarden

services:
  bitwarden:
    image: docker.io/vaultwarden/server:1.36.0
    container_name: bitwarden
    restart: unless-stopped
    ports:
      - ${APOLLON_BITWARDEN_PORT}:80
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: bitwarden
        target: /data
    labels:
      traefik-conf.port: ${APOLLON_BITWARDEN_PORT}
      homepage.group: Apollon
      homepage.name: Bitwarden
      traefik-conf.middlewares: geoblock@file
      # traefik-conf.http.routers.apollon_bitwarden_cert.rule: Host(`bitwarden.${PUBLIC_DOMAIN_NAME}`)
      # traefik-conf.http.routers.apollon_bitwarden_cert.service: apollon_bitwarden
      # traefik-conf.http.routers.apollon_bitwarden_cert.entrypoints: https
      # traefik-conf.http.routers.apollon_bitwarden_cert.app.middlewares: authelia@file
      # traefik-conf.http.routers.apollon_bitwarden_cert.tls.certResolver: tls-resolver
      # traefik-conf.http.routers.apollon_bitwarden_cert.tls.options: ca-mgarnier11@file

volumes:
  docker-data:
    external: true
