services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.19.1

    container_name: mealie
    restart: unless-stopped
    ports:
      - "${ATHENA_MEALIE_PORT}:9000"

    deploy:
      resources:
        limits:
          memory: 1000M
    labels:
      traefik-conf.port: ${ATHENA_MEALIE_PORT}
      # sablier.enable: true
      # sablier.group: mealie
      # sablier.group.strategy: dynamic
    healthcheck:
      test: python -m mealie.scripts.healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: mealie
        target: /app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      BASE_URL: https://mealie.${PUBLIC_DOMAIN_NAME}
      OIDC_AUTH_ENABLED: "true"
      OIDC_SIGNUP_ENABLED: "true"
      OIDC_CONFIGURATION_URL: "https://authelia.${PUBLIC_DOMAIN_NAME}/.well-known/openid-configuration"
      OIDC_CLIENT_ID: "mealie"
      OIDC_CLIENT_SECRET: "893d5922e782e6f5aed26244d15ecc91"
      OIDC_AUTO_REDIRECT: "false"
      OIDC_ADMIN_GROUP: "mealie-admins"
      OIDC_USER_GROUP: "mealie-users"
      ALLOW_PASSWORD_LOGIN: "false"
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: mgarnier11@gmail.com
      SMTP_PASSWORD: "wxpb dsdb pqom xfts"
      SMTP_FROM_EMAIL: mgarnier11@gmail.com

volumes:
  docker-data:
    external: true
