name: hoppscotch

services:
  hoppscotch-db:
    image: postgres:15
    user: postgres
    container_name: hoppscotch-db
    restart: unless-stopped
    env_file: ./hoppscotch-db.env
    networks:
      - hoppscotch-net
    volumes:
      - docker-data-hoppscotch-db:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  hoppscotch:
    image: hoppscotch/hoppscotch:$HOPPSCOTCH_VERSION
    container_name: hoppscotch
    restart: unless-stopped
    env_file: ./hoppscotch.env
    networks:
      - hoppscotch-net
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@hoppscotch-db:5432/$POSTGRES_DB
      MAILER_SMTP_ENABLE: true
      MAILER_USE_CUSTOM_CONFIGS: true
      MAILER_ADDRESS_FROM: $MAIL_LOGIN
      MAILER_SMTP_HOST: $MAIL_HOST
      MAILER_SMTP_PORT: $MAIL_PORT
      MAILER_SMTP_SECURE: $MAIL_SECURE
      MAILER_SMTP_USER: $MAIL_LOGIN
      MAILER_SMTP_PASSWORD: $MAIL_PASSWORD
      MAILER_TLS_REJECT_UNAUTHORIZED: false
    ports:
      - $APOLLON_HOPPSCOTCH_PORT:80
    labels:
      traefik-conf.port: $APOLLON_HOPPSCOTCH_PORT
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    # command: ["pnpx", "prisma", "migrate", "deploy"]

  # hoppscotch-back:
  #   image: hoppscotch/hoppscotch-backend:$HOPPSCOTCH_VERSION
  #   container_name: hoppscotch-back
  #   restart: unless-stopped
  #   environment:
  #     DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@hoppstoch-db:5432/$POSTGRES_DB
  #   env_file: ./hoppscotch.env
  #   networks:
  #     - hoppscotch-net
  #   ports:
  #     - $APOLLON_HOPPSCOTCH_BACK_PORT:3170
  #   labels:
  #     traefik-conf.port: $APOLLON_HOPPSCOTCH_BACK_PORT
  #   depends_on:
  #     hoppscotch-db:
  #       condition: service_healthy

  # hoppscotch-front:
  #   image: hoppscotch/hoppscotch-frontend:$HOPPSCOTCH_VERSION
  #   container_name: hoppscotch-front
  #   restart: unless-stopped
  #   env_file: ./hoppscotch.env
  #   networks:
  #     - hoppscotch-net
  #   ports:
  #     - $APOLLON_HOPPSCOTCH_FRONT_PORT:3000
  #   labels:
  #     traefik-conf.port: $APOLLON_HOPPSCOTCH_FRONT_PORT
  #     traefik-conf.name: hoppscotch
  #   depends_on:
  #     hoppscotch-back:
  #       condition: service_healthy

  # hoppscotch-admin:
  #   image: hoppscotch/hoppscotch-admin:$HOPPSCOTCH_VERSION
  #   container_name: hoppscotch-admin
  #   restart: unless-stopped
  #   env_file: ./hoppscotch.env
  #   networks:
  #     - hoppscotch-net
  #   ports:
  #     - $APOLLON_HOPPSCOTCH_ADMIN_PORT:3100
  #   labels:
  #     traefik-conf.port: $APOLLON_HOPPSCOTCH_ADMIN_PORT
  #   depends_on:
  #     hoppscotch-back:
  #       condition: service_healthy

networks:
  hoppscotch-net:

volumes:
  docker-data-hoppscotch-db:
    driver: local
    driver_opts:
      type: none
      device: ${APOLLON_DOCKER_DATA}/hoppscotch
      o: bind
