name: backup

services:
  go-autosaver:
    container_name: go-autosaver
    restart: unless-stopped
    image: mgarnier11/go-autosaver:${GO_AUTOSAVER_VERSION}
    volumes:
      - /hdd-2/backups:/local-backups
      - docker-data:/backups/docker-data-athena
      - docker-data-autosaver:/config
    ports:
      - ${ATHENA_AUTOSAVER_PORT}:8080
    labels:
      traefik-conf.port: ${ATHENA_AUTOSAVER_PORT}
      traefik-conf.name: autosaver.athena
    privileged: true
    environment:
      # CRON_SCHEDULE: 15 4 * * *
      CONFIG_FILE_PATH: /config/config.yml
      # KEEP_ALIVE_URL: https://autosaver.athena.int.mgarnier11.fr
      # LOG_LEVEL: 5
      NTFY_SERVER: ${NTFY_SERVER}
      NTFY_TOPIC: ${NTFY_TOPIC}
    secrets:
      - ssh_private_key

volumes:
  docker-data:
    driver: local
    driver_opts:
      type: none
      device: ${ATHENA_DOCKER_DATA}
      o: bind

  docker-data-autosaver:
    driver: local
    driver_opts:
      type: none
      device: ${ATHENA_DOCKER_DATA}/autosaver
      o: bind

secrets:
  ssh_private_key:
    environment: "SSH_PRIVATE_KEY"
