name: backup

services:
  go-autosaver:
    container_name: go-autosaver
    restart: unless-stopped
    image: mgarnier11/go-autosaver:${GO_AUTOSAVER_VERSION}
    volumes:
      - docker-data-local:/backups
      - type: volume
        source: docker-data
        volume:
          subpath: autosaver
        target: /config
    ports:
      - ${ATHENA_AUTOSAVER_PORT}:8080
    labels:
      traefik-conf.port: ${ATHENA_AUTOSAVER_PORT}
      traefik-conf.name: autosaver.athena
    privileged: true
    environment:
      # CRON_SCHEDULE: 15 4 * * *
      CONFIG_FILE_PATH: /config/config-athena.yml
      # LOG_LEVEL: 5
      NTFY_SERVER: ${NTFY_SERVER}
      NTFY_TOPIC: ${NTFY_TOPIC}
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:8080 || exit 1
      start_period: 10s
volumes:
  docker-data-local:
    driver: local
    driver_opts:
      type: none
      device: ${ATHENA_DOCKER_DATA}
      o: bind

  docker-data:
    external: true
