name: backup

services:
  go-autosaver:
    container_name: go-autosaver
    restart: unless-stopped
    image: docker.io/mgarnier11/go-autosaver:1.1.1@sha256:e3fcbfd114df998b75cd122ee730047f80ee94d90b6e7e0b432a60f898736e0c
    volumes:
      - docker-data:/backups
      - type: volume
        source: docker-data
        volume:
          subpath: backup/autosaver
        target: /config
    ports:
      - ${ATLAS_AUTOSAVER_PORT}:8080
    labels:
      traefik-conf.port: ${ATLAS_AUTOSAVER_PORT}
      traefik-conf.name: autosaver.atlas
      homepage.group: Atlas
      homepage.name: Autosaver
    privileged: true
    environment:
      CONFIG_FILE_PATH: /config/config-atlas.yml
      # LOG_LEVEL: 5
      NTFY_SERVER: ${NTFY_SERVER}
      NTFY_TOPIC: ${NTFY_TOPIC}
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
volumes:
  docker-data:
    external: true
