name: backup

services:
  # go-autosaver:
  #   container_name: go-autosaver
  #   restart: unless-stopped
  #   image: mgarnier11/go-autosaver:${GO_AUTOSAVER_VERSION}
  #   volumes:
  #     - docker-data-local:/backups
  #     - type: volume
  #       source: docker-data
  #       volume:
  #         subpath: autosaver
  #       target: /config
  #   ports:
  #     - ${ZEPHYR_AUTOSAVER_PORT}:8080
  #   labels:
  #     traefik-conf.port: ${ZEPHYR_AUTOSAVER_PORT}
  #     traefik-conf.name: autosaver.zephyr
  #   privileged: true
  #   environment:
  #     CONFIG_FILE_PATH: /config/config-zephyr.yml
  #     # LOG_LEVEL: 5
  #     NTFY_SERVER: ${NTFY_SERVER}
  #     NTFY_TOPIC: ${NTFY_TOPIC}
  #     SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}

  cron-runner:
    container_name: cron-runner
    restart: unless-stopped
    image: mgarnier11/cron-runner:${CRON_RUNNER_VERSION}
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: backup/cron-runner
        target: /config
    ports:
      - ${ZEPHYR_CRON_RUNNER_PORT}:3000
    labels:
      traefik-conf.port: ${ZEPHYR_CRON_RUNNER_PORT}
    environment:
      LOG_LEVEL: 5
      CRON_CONFIG_PATH: /config/config.yml

volumes:
  docker-data-local:
    driver: local
    driver_opts:
      type: none
      device: ${ZEPHYR_DOCKER_DATA}
      o: bind
  docker-data:
    external: true
