name: orchestrator

services:
  orchestrator:
    container_name: orchestrator
    restart: unless-stopped
    image: docker.io/mgarnier11/orchestrator:2.0.0
    ports:
      - ${ZEPHYR_ORCHESTRATOR_PORT}:3000
    environment:
      ORCHESTRATOR_COMPOSE_DIRECTORY: /compose
      ATHENA_HOST: ssh://${SSH_USER}@${ATHENA_IP}
      ZEPHYR_HOST: ssh://${SSH_USER}@${ZEPHYR_IP}
      APOLLON_HOST: ssh://${SSH_USER}@${APOLLON_IP}
      ATLAS_HOST: ssh://${SSH_USER}@${ATLAS_IP}
      ORCHESTRATOR_SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    labels:
      traefik-conf.port: ${ZEPHYR_ORCHESTRATOR_PORT}
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: orchestrator
        target: /compose

volumes:
  docker-data:
    external: true
  # docker-data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: ${ZEPHYR_DOCKER_DATA}/orchestrator
  #     o: bind
