name: ntfy

services:
  ntfy:
    image: binwiederhier/ntfy:${NTFY_VERSION}
    container_name: ntfy
    restart: unless-stopped
    command:
      - serve
    environment:
      TZ: ${TIMEZONE}
    ports:
      - ${APOLLON_NTFY_PORT}:80
    volumes:
      - docker-data-ntfy:/etc/ntfy
    labels:
      traefik-conf.port: ${APOLLON_NTFY_PORT}
    healthcheck:
      test: wget -q --tries=1 http://localhost/v1/health -O - | grep -Eo '\"healthy\":true' || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  docker-data-ntfy:
    driver: local
    driver_opts:
      type: none
      device: ${APOLLON_DOCKER_DATA}/ntfy
      o: bind
