name: monitoring

services:
  docker-socket-proxy:
    image: docker.io/tecnativa/docker-socket-proxy:v0.5.0@sha256:1f5038b54f06c3e18422902cf00ba21803d1c97805aae032e5e6673d532d3459
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    ports:
      - ${ATHENA_DOCKER_SOCKET_PROXY_PORT}:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  telegraf:
    image: docker.io/telegraf:1.39.2@sha256:386b2d4fdd4265d9e5b6a20131dbfe2b6bc277a4d53972962e5a4a3d16f180ef
    container_name: telegraf
    restart: unless-stopped
    command: ["--config", "/config/athena.conf"]
    user: telegraf:989 # required for docker socket access, got from : stat -c '%g' /var/run/docker.sock
    network_mode: host # required for host-level metrics
    runtime: nvidia # required for GPU metrics
    devices:
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia0:/dev/nvidia0
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/telegraf
        target: /config
      # - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      # GPU metrics (if using NVIDIA GPUs)
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /usr/bin/nvidia-smi:/usr/bin/nvidia-smi:ro
      - /usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/x86_64-linux-gnu/nvidia:ro
    environment:
      LD_PRELOAD: /usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_MOUNT_PREFIX: /hostfs
      INFLUX_URL: "http://${ATLAS_IP}:${ATLAS_INFLUXDB_PORT}"
      INFLUX_TOKEN: ${INFLUXDB_TOKEN}
      INFLUX_ORG: ${INFLUXDB_ORG}
      INFLUX_BUCKET: ${INFLUXDB_BUCKET}

  dozzle-agent:
    image: docker.io/amir20/dozzle:v10.7.1@sha256:a8441e9d2928cc7b30d0023f5eedbb87ef6e234d87f3be02662bd8f417955b8b
    container_name: dozzle-agent
    restart: unless-stopped
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - ${ATHENA_DOZZLE_AGENT_PORT}:7007

volumes:
  docker-data:
    external: true
