name: monitoring

services:
  docker-socket-proxy:
    image: docker.io/tecnativa/docker-socket-proxy:v0.4.2@sha256:1f3a6f303320723d199d2316a3e82b2e2685d86c275d5e3deeaf182573b47476
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    ports:
      - ${ATHENA_DOCKER_SOCKET_PROXY_PORT}:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  telegraf:
    image: docker.io/telegraf:1.38.4@sha256:fb0a95f7a42958b1e7219faf075552795f7e043432a28c54baf070442b6259ee
    container_name: telegraf
    restart: unless-stopped
    command: ["--config", "/config/athena.conf"]
    user: telegraf:989 # required for docker socket access, got from : stat -c '%g' /var/run/docker.sock
    network_mode: host # required for host-level metrics
    runtime: nvidia # required for GPU metrics
    devices:
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia0:/dev/nvidia0
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/telegraf
        target: /config
      # - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      # GPU metrics (if using NVIDIA GPUs)
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /usr/bin/nvidia-smi:/usr/bin/nvidia-smi:ro
      - /usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/x86_64-linux-gnu/nvidia:ro
    environment:
      LD_PRELOAD: /usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_MOUNT_PREFIX: /hostfs
      INFLUX_URL: "http://${APOLLON_IP}:${APOLLON_INFLUXDB_PORT}"
      INFLUX_TOKEN: ${INFLUXDB_TOKEN}
      INFLUX_ORG: ${INFLUXDB_ORG}
      INFLUX_BUCKET: ${INFLUXDB_BUCKET}

  dozzle-agent:
    image: docker.io/amir20/dozzle:v10.6.3@sha256:3d42f4c7b27f475117004f8524b52b6ea2cc1cdc39a508892d6b81ffb2883160
    container_name: dozzle-agent
    restart: unless-stopped
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - ${ATHENA_DOZZLE_AGENT_PORT}:7007

  beszel-agent:
    image: docker.io/henrygd/beszel-agent:0.18.7@sha256:8874e2c53f9de5e063a6a80d6b617e20fa593ac5dc4eb4c6ce1f912f510f38f8
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PORT: ${ATHENA_BESZEL_AGENT_PORT}
      KEY: ${BESZEL_AGENT_KEY}
    healthcheck:
      test: ["CMD", "/agent", "health"]
      start_period: 10s

volumes:
  docker-data:
    external: true
