name: monitoring

services:
  docker-socket-proxy:
    image: docker.io/tecnativa/docker-socket-proxy:v0.5.0@sha256:1f5038b54f06c3e18422902cf00ba21803d1c97805aae032e5e6673d532d3459
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    ports:
      - ${ATLAS_DOCKER_SOCKET_PROXY_PORT}:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:2375/_ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  telegraf:
    image: docker.io/telegraf:1.39.3@sha256:ac66e6482c0644765c12904ce2f42ce3f3702f72e905b1894120b51b12ae30c9
    container_name: telegraf
    restart: unless-stopped
    command: ["--config", "/config/atlas.conf"]
    network_mode: host # required for host-level metrics
    user: telegraf:989 # required for docker socket access, got from : stat -c '%g' /var/run/docker.sock
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/telegraf
        target: /config
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    environment:
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_MOUNT_PREFIX: /hostfs
      INFLUX_URL: "http://${ATLAS_IP}:${ATLAS_INFLUXDB_PORT}"
      INFLUX_TOKEN: ${INFLUXDB_TOKEN}
      INFLUX_ORG: ${INFLUXDB_ORG}
      INFLUX_BUCKET: ${INFLUXDB_BUCKET}
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  dozzle-agent:
    image: docker.io/amir20/dozzle:v10.9.0@sha256:7f01a2504f89788b60ad0efddd94472fd66f9a225c708356cdb815d9d8abd184
    container_name: dozzle-agent
    restart: unless-stopped
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - ${ATLAS_DOZZLE_AGENT_PORT}:7007

  grafana:
    container_name: grafana
    image: docker.io/grafana/grafana:13.2.1@sha256:f772d434e8fab0049deb2b1b30abd43342bcfca1537614aa8d36080232cf4283
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PWD}
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - ${ATLAS_GRAFANA_PORT}:3000
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/grafana/data
        target: /var/lib/grafana
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/grafana/conf
        target: /etc/grafana
    labels:
      traefik-conf.port: ${ATLAS_GRAFANA_PORT}
      traefik-conf.middlewares: ip-wl@file,geoblock@file,authelia@file,grafana-headers@file
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:3000/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  influxdb:
    container_name: influxdb
    image: docker.io/influxdb:2.9.1@sha256:f75e48af0598e8aec7986e991a848d19a119101a7d563a2e5db1dfaac9c45daa
    restart: unless-stopped
    ports:
      - ${ATLAS_INFLUXDB_PORT}:8086
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/influxdb
        target: /var/lib/influxdb2
    environment:
      # DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PWD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
    labels:
      traefik-conf.port: ${ATLAS_INFLUXDB_PORT}
    healthcheck:
      test: influx ping || exit 1
      start_period: 10s
      interval: 30s
      retries: 3

  openobserve:
    image: docker.io/openobserve/openobserve:v0.92.2@sha256:88fb692ac791d3eaff69653a4a4686f1c7eceb9e105491d58d29ac2739560b3b
    container_name: openobserve
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: ${OPENOBSERVE_ROOT_EMAIL}
      ZO_ROOT_USER_PASSWORD: ${OPENOBSERVE_ROOT_PASSWORD}
      ZO_DATA_DIR: /data
      ZO_COMPACT_DATA_RETENTION_DAYS: 30
    ports:
      - ${ATLAS_OPENOBSERVE_PORT}:5080
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/openobserve
        target: /data
    labels:
      traefik-conf.port: ${ATLAS_OPENOBSERVE_PORT}

  vector:
    image: docker.io/timberio/vector:0.58.0-debian@sha256:1c1ea358c617ea0b23003d5af87f7a678b30f8f7096437e680380c47fc13d2d9
    container_name: vector
    restart: unless-stopped
    user: root:root # required for docker socket access; replace root:root with vector:<docker-gid> for least-privilege
    command: ["--config", "/config/vector.toml"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/vector
        target: /config
    environment:
      HOST_NAME: ${ATLAS_HOSTNAME}
      OPENOBSERVE_HOST: ${ATLAS_IP}
      OPENOBSERVE_PORT: ${ATLAS_OPENOBSERVE_PORT}
      OPENOBSERVE_ROOT_EMAIL: ${OPENOBSERVE_ROOT_EMAIL}
      OPENOBSERVE_ROOT_PASSWORD: ${OPENOBSERVE_ROOT_PASSWORD}
    depends_on:
      - openobserve
    healthcheck:
      test:
        - "CMD-SHELL"
        - >
          bash -c 'exec 3<>/dev/tcp/localhost/8686 &&
          echo -e "GET /health HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3 &&
          head -n 1 <&3 | grep -q "200"' || exit 1      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  docker-data:
    external: true
