name: monitoring

services:
  docker-socket-proxy:
    image: docker.io/tecnativa/docker-socket-proxy:v0.4.2@sha256:1f3a6f303320723d199d2316a3e82b2e2685d86c275d5e3deeaf182573b47476
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    ports:
      - ${ATLAS_DOCKER_SOCKET_PROXY_PORT}:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  telegraf:
    image: docker.io/telegraf:1.39.2@sha256:49899960eccad39415b91cf654324f0bb7efddaef8f1aa3ec24e2d8c6e19618e
    container_name: telegraf
    restart: unless-stopped
    command: ["--config", "/config/atlas.conf"]
    network_mode: host # required for host-level metrics
    user: telegraf:989 # required for docker socket access, got from : stat -c '%g' /var/run/docker.sock
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/telegraf
        target: /config
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    environment:
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_MOUNT_PREFIX: /hostfs
      INFLUX_URL: "http://${APOLLON_IP}:${APOLLON_INFLUXDB_PORT}"
      INFLUX_TOKEN: ${INFLUXDB_TOKEN}
      INFLUX_ORG: ${INFLUXDB_ORG}
      INFLUX_BUCKET: ${INFLUXDB_BUCKET}

  dozzle-agent:
    image: docker.io/amir20/dozzle:v10.6.11@sha256:bc1ee4ba8d66c7fc0d03823a78486165fb219809f79eaf54cecf3114d647ab14
    container_name: dozzle-agent
    restart: unless-stopped
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - ${ATLAS_DOZZLE_AGENT_PORT}:7007

  beszel-agent:
    image: docker.io/henrygd/beszel-agent:0.18.7@sha256:8874e2c53f9de5e063a6a80d6b617e20fa593ac5dc4eb4c6ce1f912f510f38f8
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PORT: ${ATLAS_BESZEL_AGENT_PORT}
      KEY: ${BESZEL_AGENT_KEY}
    healthcheck:
      test: ["CMD", "/agent", "health"]
      start_period: 10s

volumes:
  docker-data:
    external: true
