services:
  nodesight:
    image: mgarnier11/nodesight:${NODESIGHT_VERSION}
    container_name: nodesight
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /:/mnt/host:ro
  # whatsupdocker:
  #   image: getwud/wud:${WUD_VERSION}
  #   container_name: wud
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
