name: monitoring

services:
  docker-socket-proxy:
    image: docker.io/tecnativa/docker-socket-proxy:v0.4.2@sha256:1f3a6f303320723d199d2316a3e82b2e2685d86c275d5e3deeaf182573b47476
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    ports:
      - ${ZEPHYR_DOCKER_SOCKET_PROXY_PORT}:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  telegraf:
    image: docker.io/telegraf:1.39.0@sha256:9768f82ebf8bde6da0d61ba220c00161750740c3e322b507a5982b89bbfca99a
    container_name: telegraf
    restart: unless-stopped
    command:
      - --config
      - /config/zephyr.conf
    network_mode: host # required for host-level metrics
    user: telegraf:985 # required for docker socket access, got from : stat -c '%g' /var/run/docker.sock
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/telegraf
        target: /config
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    environment:
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
      INFLUX_URL: "http://${APOLLON_IP}:${APOLLON_INFLUXDB_PORT}"
      INFLUX_TOKEN: ${INFLUXDB_TOKEN}
      INFLUX_ORG: ${INFLUXDB_ORG}
      INFLUX_BUCKET: ${INFLUXDB_BUCKET}

  dozzle-agent:
    image: docker.io/amir20/dozzle:v10.6.5@sha256:fa12525776bf665147d82bf031ff262ee89a0a12454122558a353ec38ada4aaf
    container_name: dozzle-agent
    restart: unless-stopped
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - ${ZEPHYR_DOZZLE_AGENT_PORT}:7007

  dozzle:
    image: docker.io/amir20/dozzle:v10.6.5@sha256:fa12525776bf665147d82bf031ff262ee89a0a12454122558a353ec38ada4aaf
    container_name: dozzle
    restart: unless-stopped
    environment:
      DOZZLE_REMOTE_AGENT: >
        ${ZEPHYR_IP}:${ZEPHYR_DOZZLE_AGENT_PORT},
        ${ATHENA_IP}:${ATHENA_DOZZLE_AGENT_PORT},
        ${APOLLON_IP}:${APOLLON_DOZZLE_AGENT_PORT},
        ${ATLAS_IP}:${ATLAS_DOZZLE_AGENT_PORT}
    ports:
      - ${ZEPHYR_DOZZLE_PORT}:8080
    labels:
      traefik-conf.port: ${ZEPHYR_DOZZLE_PORT}
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  beszel:
    image: docker.io/henrygd/beszel:0.18.7@sha256:a849ad80814b6a1a3be665304dcace5d4854b3bed7bde4dd1227e8ce1b82d477
    container_name: beszel
    restart: unless-stopped
    ports:
      - ${ZEPHYR_BESZEL_PORT}:8090
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/beszel
        target: /beszel_data
    labels:
      traefik-conf.port: ${ZEPHYR_BESZEL_PORT}
    healthcheck:
      # The URL is relative to the container, not the host
      test:
        [
          "CMD",
          "/beszel",
          "health",
          "--url",
          "http://localhost:${ZEPHYR_BESZEL_PORT}",
        ]
      start_period: 10s

  beszel-agent:
    image: docker.io/henrygd/beszel-agent:0.18.7@sha256:8874e2c53f9de5e063a6a80d6b617e20fa593ac5dc4eb4c6ce1f912f510f38f8
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PORT: ${ZEPHYR_BESZEL_AGENT_PORT}
      KEY: ${BESZEL_AGENT_KEY}
    healthcheck:
      test: ["CMD", "/agent", "health"]
      start_period: 10s

  # dashboard:
  #   container_name: dashboard
  #   restart: unless-stopped
  #   image: mgarnier11/dashboard:${DASHBOARD_VERSION}
  #   environment:
  #     APP_CONF_PATH: /config/conf.yml
  #     ICONS_PATH: /config/icons
  #   volumes:
  #     - type: volume
  #       source: docker-data
  #       volume:
  #         subpath: monitoring/dashboard
  #       target: /config
  #   ports:
  #     - ${ZEPHYR_DASHBOARD_PORT}:3000
  #   labels:
  #     traefik-conf.port: ${ZEPHYR_DASHBOARD_PORT}
  #     traefik-conf.name: dashboard-old

  homepage:
    image: docker.io/mgarnier11/homepage@sha256:367c5ad8c66ed7cefec5cc296e0daee96556b407f32496703f0a4ed396c0f83f
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.${PUBLIC_DOMAIN_NAME}
      # PUID: 1000 # optional, your user id
      # PGID: 1000 # optional, your group id
      APOLLON_IP: ${APOLLON_IP}
      ATHENA_IP: ${ATHENA_IP}
      ATLAS_IP: ${ATLAS_IP}
      ZEPHYR_IP: ${ZEPHYR_IP}
    env_file:
      - ../ports.env
    ports:
      - ${ZEPHYR_HOMEPAGE_PORT}:3000
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/homepage/config
        target: /app/config
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/homepage/images
        target: /app/images
    restart: unless-stopped
    labels:
      traefik-conf.port: ${ZEPHYR_HOMEPAGE_PORT}

volumes:
  docker-data:
    external: true
