name: monitoring

services:
  telegraf:
    image: telegraf:${TELEGRAF_VERSION}
    container_name: telegraf
    restart: unless-stopped
    command:
      - --config
      - /config/zephyr.conf
    network_mode: host # required for host-level metrics
    user: telegraf:992 # required for docker socket access, got from : stat -c '%g' /var/run/docker.sock
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/telegraf
        target: /config
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    environment:
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
      INFLUX_URL: "http://${ZEPHYR_IP}:${ZEPHYR_INFLUXDB_PORT}"
      INFLUX_TOKEN: ${INFLUXDB_TOKEN}
      INFLUX_ORG: ${INFLUXDB_ORG}
      INFLUX_BUCKET: ${INFLUXDB_BUCKET}

  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION}
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PWD}
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - ${ZEPHYR_GRAFANA_PORT}:3000
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/grafana/data
        target: /var/lib/grafana
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/grafana/conf
        target: /etc/grafana
    labels:
      traefik-conf.port: ${ZEPHYR_GRAFANA_PORT}

  influxdb:
    container_name: influxdb
    image: influxdb:${INFLUXDB_VERSION}
    restart: unless-stopped
    ports:
      - ${ZEPHYR_INFLUXDB_PORT}:8086
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/influxdb
        target: /var/lib/influxdb2
    environment:
      # DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PWD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
    labels:
      traefik-conf.port: ${ZEPHYR_INFLUXDB_PORT}
    healthcheck:
      test: influx ping || exit 1
      start_period: 10s
volumes:
  docker-data:
    external: true
