name: monitoring

services:
  docker-socket-proxy:
    image: docker.io/tecnativa/docker-socket-proxy:v0.5.0@sha256:1f5038b54f06c3e18422902cf00ba21803d1c97805aae032e5e6673d532d3459
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    ports:
      - ${ZEPHYR_DOCKER_SOCKET_PROXY_PORT}:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:2375/_ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  telegraf:
    image: docker.io/telegraf:1.39.3@sha256:b5b8291d62bf7ccc222bdacfd7229b6cc7227f1d07574ca4eb0a872e5a8f83cd
    container_name: telegraf
    restart: unless-stopped
    command:
      - --config
      - /config/zephyr.conf
    network_mode: host # required for host-level metrics
    user: telegraf:985 # required for docker socket access, got from : stat -c '%g' /var/run/docker.sock
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/telegraf
        target: /config
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    environment:
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
      INFLUX_URL: "http://${ATLAS_IP}:${ATLAS_INFLUXDB_PORT}"
      INFLUX_TOKEN: ${INFLUXDB_TOKEN}
      INFLUX_ORG: ${INFLUXDB_ORG}
      INFLUX_BUCKET: ${INFLUXDB_BUCKET}
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  dozzle-agent:
    image: docker.io/amir20/dozzle:v10.7.3@sha256:c32ca7a443796de62a07afd621b17b6c6c073320cd8431493bb1fd84e3a1eff8
    container_name: dozzle-agent
    restart: unless-stopped
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - ${ZEPHYR_DOZZLE_AGENT_PORT}:7007

  dozzle:
    image: docker.io/amir20/dozzle:v10.7.3@sha256:c32ca7a443796de62a07afd621b17b6c6c073320cd8431493bb1fd84e3a1eff8
    container_name: dozzle
    restart: unless-stopped
    environment:
      DOZZLE_REMOTE_AGENT: >
        ${ZEPHYR_IP}:${ZEPHYR_DOZZLE_AGENT_PORT},
        ${ATHENA_IP}:${ATHENA_DOZZLE_AGENT_PORT},
        ${APOLLON_IP}:${APOLLON_DOZZLE_AGENT_PORT},
        ${ATLAS_IP}:${ATLAS_DOZZLE_AGENT_PORT}
    ports:
      - ${ZEPHYR_DOZZLE_PORT}:8080
    labels:
      traefik-conf.port: ${ZEPHYR_DOZZLE_PORT}
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # dashboard:
  #   container_name: dashboard
  #   restart: unless-stopped
  #   image: mgarnier11/dashboard:${DASHBOARD_VERSION}
  #   environment:
  #     APP_CONF_PATH: /config/conf.yml
  #     ICONS_PATH: /config/icons
  #   volumes:
  #     - type: volume
  #       source: docker-data
  #       volume:
  #         subpath: monitoring/dashboard
  #       target: /config
  #   ports:
  #     - ${ZEPHYR_DASHBOARD_PORT}:3000
  #   labels:
  #     traefik-conf.port: ${ZEPHYR_DASHBOARD_PORT}
  #     traefik-conf.name: dashboard-old

  homepage:
    image: docker.io/mgarnier11/homepage@sha256:367c5ad8c66ed7cefec5cc296e0daee96556b407f32496703f0a4ed396c0f83f
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.${PUBLIC_DOMAIN_NAME}
      # PUID: 1000 # optional, your user id
      # PGID: 1000 # optional, your group id
      APOLLON_IP: ${APOLLON_IP}
      ATHENA_IP: ${ATHENA_IP}
      ATLAS_IP: ${ATLAS_IP}
      ZEPHYR_IP: ${ZEPHYR_IP}
    # env_file:
    #   - ../ports.env
    ports:
      - ${ZEPHYR_HOMEPAGE_PORT}:3000
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/homepage/config
        target: /app/config
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/homepage/images
        target: /app/images
    restart: unless-stopped
    labels:
      traefik-conf.port: ${ZEPHYR_HOMEPAGE_PORT}

  vector:
    image: docker.io/timberio/vector:0.57.0-debian@sha256:ed2134fa8f9844c1ca6405260903c2c2c52f94af9e16bc8fa9de9655134e0b39
    container_name: vector
    restart: unless-stopped
    user: root:root # required for docker socket access; replace root:root with vector:<docker-gid> for least-privilege
    command: ["--config", "/config/vector.toml"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: docker-data
        volume:
          subpath: monitoring/vector
        target: /config
    environment:
      HOST_NAME: ${ZEPHYR_HOSTNAME}
      OPENOBSERVE_HOST: ${ATLAS_IP}
      OPENOBSERVE_PORT: ${ATLAS_OPENOBSERVE_PORT}
      OPENOBSERVE_ROOT_EMAIL: ${OPENOBSERVE_ROOT_EMAIL}
      OPENOBSERVE_ROOT_PASSWORD: ${OPENOBSERVE_ROOT_PASSWORD}
    healthcheck:
      test:
        - "CMD-SHELL"
        - >
          bash -c 'exec 3<>/dev/tcp/localhost/8686 &&
          echo -e "GET /health HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3 &&
          head -n 1 <&3 | grep -q "200"' || exit 1      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  docker-data:
    external: true
