name: media

services:
  jdownloader:
    container_name: jdownloader
    restart: unless-stopped
    image: docker.io/jlesage/jdownloader-2:v26.07.2@sha256:47ee6c64917ca5326516ebe868714709c6bdd2e08ca0e33f6e80a943ef2019d2
    ports:
      - ${ATHENA_JDOWNLOADER_PORT}:5800
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: media/jdownloader
        target: /config
      - type: volume
        source: atlas-media
        target: /output
    labels:
      traefik-conf.port: ${ATHENA_JDOWNLOADER_PORT}
      # sablier.enable: true
      # sablier.group: downloader
      # sablier.group.strategy: dynamic

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TIMEZONE: ${TIMEZONE}
      # - NVIDIA_VISIBLE_DEVICES=all
      # - JDOWNLOADER_PUBLISHED_SERVER_URL=
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:5800 || exit 1
      start_period: 10s

  jellyfin:
    container_name: jellyfin
    restart: unless-stopped
    image: docker.io/jellyfin/jellyfin:10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
    ports:
      - ${ATHENA_JELLYFIN_PORT}:8096
    labels:
      traefik-conf.port: ${ATHENA_JELLYFIN_PORT}
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      # - NVIDIA_VISIBLE_DEVICES=all
      # - JELLYFIN_PublishedServerUrl=192.168.0.5
    volumes:
      - type: volume
        source: docker-data-local
        volume:
          subpath: jellyfin/config
        target: /config
      - type: volume
        source: docker-data-local
        volume:
          subpath: jellyfin/cache
        target: /cache
      - type: volume
        source: atlas-media
        target: /media
      # - /big-hdd/media:/media
    # group_add:
    #   - 105
    # devices:
    #   - /dev/dri/renderD128:/dev/dri/renderD128
    # security_opt:
    #   - seccomp:unconfined
    healthcheck:
      test: curl -f http://localhost:8096 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  navidrome-music:
    image: docker.io/deluan/navidrome:0.63.2@sha256:9012939114fbb1bb641b81cf96dec5ded15f0aafefe8d47a511d7cb919658e40
    container_name: navidrome-music
    user: 1000:1000 # should be owner of volumes
    ports:
      - ${ATHENA_MEDIA_MUSIC_PORT}:4533
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      # ND_BASEURL=""
      ND_SPOTIFY_ID: ${SPOTIFY_ID}
      ND_SPOTIFY_SECRET: ${SPOTIFY_SECRET}
      ND_ARTISTARTPRIORITY: external
      ND_REVERSEPROXYWHITELIST: 0.0.0.0/0
      ND_ENABLEUSEREDITING: false
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: media/navidrome-music
        target: /data
      - type: volume
        source: atlas-media
        volume:
          subpath: musics
        target: /music
        read_only: true
    labels:
      traefik-conf.port: ${ATHENA_MEDIA_MUSIC_PORT}
      traefik-conf.name: music
      traefik-conf.http.routers.athena_music_api.rule: Host(`music.${PUBLIC_DOMAIN_NAME}`) && PathPrefix(`/rest/`) && !Query(`c`, `NavidromeUI`)
      traefik-conf.http.routers.athena_music_api.service: athena_music
      traefik-conf.http.routers.athena_music_api.entrypoints: https
      traefik-conf.http.routers.athena_music_api.middlewares: ip-wl@file,geoblock@file,authelia-basic@file
      traefik-conf.http.routers.athena_music_api.tls.certResolver: tls-resolver

  navidrome-sagas:
    image: docker.io/deluan/navidrome:0.63.2@sha256:9012939114fbb1bb641b81cf96dec5ded15f0aafefe8d47a511d7cb919658e40
    container_name: navidrome-sagas
    user: 1000:1000 # should be owner of volumes
    ports:
      - ${ATHENA_MEDIA_SAGAS_PORT}:4533
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      # ND_BASEURL=""
      ND_SPOTIFY_ID: ${SPOTIFY_ID}
      ND_SPOTIFY_SECRET: ${SPOTIFY_SECRET}
      ND_REVERSEPROXYWHITELIST: 0.0.0.0/0
      ND_ENABLEUSEREDITING: false
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: media/navidrome-sagas
        target: /data
      - type: volume
        source: atlas-media
        volume:
          subpath: sagas-mp3
        target: /music
        read_only: true
    labels:
      traefik-conf.port: ${ATHENA_MEDIA_SAGAS_PORT}
      traefik-conf.name: sagas
      traefik-conf.http.routers.athena_sagas_api.rule: Host(`sagas.${PUBLIC_DOMAIN_NAME}`) && PathPrefix(`/rest/`) && !Query(`c`, `NavidromeUI`)
      traefik-conf.http.routers.athena_sagas_api.service: athena_sagas
      traefik-conf.http.routers.athena_sagas_api.entrypoints: https
      traefik-conf.http.routers.athena_sagas_api.middlewares: ip-wl@file,geoblock@file,authelia-basic@file
      traefik-conf.http.routers.athena_sagas_api.tls.certResolver: tls-resolver

  downloader:
    image: registry.gitlab.com/bockiii/deemix-docker@sha256:d325660d833c30c8bbb5cf0caa75135b42a2f69b82f2269fd5bea91a04c449e6
    container_name: downloader
    restart: unless-stopped
    ports:
      - ${ATHENA_DOWNLOADER_PORT}:6595
    labels:
      traefik-conf.port: ${ATHENA_DOWNLOADER_PORT}
      # sablier.enable: true
      # sablier.group: downloader
      # sablier.group.strategy: dynamic
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK_SET: 022
      DEEMIX_SINGLE_USER: true
    volumes:
      - type: volume
        source: atlas-media
        volume:
          subpath: musics
        target: /downloads
      - type: volume
        source: docker-data
        volume:
          subpath: media/downloader
        target: /config
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://127.0.0.1:6595 || exit 1
      start_period: 10s

  # handbrake-server:
  #   image: ghcr.io/thenickoftime/handbrake-web-server:${HANDBRAKE_WEB_VERSION}
  #   container_name: handbrake-web-server
  #   user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
  #   ports:
  #     - ${ATHENA_HANDBRAKE_WEB_PORT}:9999
  #   restart: unless-stopped
  #   labels:
  #     traefik-conf.port: ${ATHENA_HANDBRAKE_WEB_PORT}
  #     traefik-conf.name: handbrake
  #   volumes:
  #     - type: volume
  #       source: docker-data
  #       volume:
  #         subpath: media/handbrake
  #       target: /data
  #     - type: volume
  #       source: atlas-media
  #       target: /video

  # handbrake-worker:
  #   image: ghcr.io/thenickoftime/handbrake-web-worker:${HANDBRAKE_WEB_VERSION}
  #   container_name: handbrake-web-worker
  #   user: 1000:1000 # edit to run as user (uuid:guid) with permissions to access your media. 0:0 to run as root (not recommended).
  #   restart: unless-stopped
  #   environment:
  #     - WORKER_ID=handbrake-worker # give your worker a unique name
  #     - SERVER_URL=handbrake-web-server
  #     # - SERVER_URL=https://handbrake.${PUBLIC_DOMAIN_NAME} # change if setting up a standalone worker, prefix with http(s):// if necessary
  #     - SERVER_PORT=9999 # change if your server is running on a non-default port
  #   volumes:
  #     - type: volume
  #       source: atlas-media
  #       target: /video
  #   depends_on:
  #     - handbrake-server
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities:
  #               - gpu
  #               - compute
  #               - video

volumes:
  docker-data:
    external: true

  docker-data-local:
    driver: local
    driver_opts:
      type: none
      device: ${ATHENA_DOCKER_DATA}
      o: bind

  atlas-media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=100.64.98.98,rw
      device: :/export/media
