name: network

services:
  traefik:
    container_name: traefik
    restart: unless-stopped
    image: docker.io/traefik:v3.7@sha256:652929a140a32d7cafafb13c6cdfab5376cfeff800f51397b87b524501ed02a8
    # image: mgarnier11/traefik-conf
    networks:
      traefik-net:
        ipv4_address: 172.19.0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: docker-data
        volume:
          subpath: network/traefik/certs
        target: /certs
      - type: volume
        source: docker-data
        volume:
          subpath: network/traefik/data
        target: /data
      - type: volume
        source: docker-data
        volume:
          subpath: network/traefik/logs
        target: /logs
    ports:
      - 80:80/tcp # Exposé à l'extérieur via : sudo ufw route allow proto tcp to 172.19.0.2 port 80
      - 443:443/tcp # Exposé à l'extérieur via : sudo ufw route allow proto tcp to 172.19.0.2 port 443
      - ${APOLLON_TRAEFIK_PORT}:8080/tcp
    labels:
      traefik-conf.port: ${APOLLON_TRAEFIK_PORT}
      # traefik-conf.name: traefik.apollon
    environment:
      TZ: Europe/Paris
      ZEPHYR_IP: ${ZEPHYR_IP}
      APOLLON_IP: ${APOLLON_IP}
      ATHENA_IP: ${ATHENA_IP}
      ATLAS_IP: ${ATLAS_IP}
      OVH_ENDPOINT: ${OVH_ENDPOINT}
      OVH_APPLICATION_KEY: ${OVH_APPLICATION_KEY}
      OVH_APPLICATION_SECRET: ${OVH_APPLICATION_SECRET}
      OVH_CONSUMER_KEY: ${OVH_CONSUMER_KEY}
    depends_on:
      - traefik-conf
    command:
      - --configFile=/data/static.yml
      - --ping=true
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:8080/ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  traefik-log-dashboard-agent:
    image: docker.io/hhftechnology/traefik-log-dashboard-agent:3.1.1@sha256:4c9853d486a0e3108678fd00aeda86ce1b269c0ae1b1c2ab9e5c81760e12d53a
    container_name: traefik-log-dashboard-agent
    restart: unless-stopped
    networks:
      traefik-net:
        ipv4_address: 172.19.0.5
    depends_on:
      - traefik
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: network/traefik/logs
        target: /logs
        read_only: true
    environment:
      TRAEFIK_LOG_DASHBOARD_ACCESS_PATH: /logs/traefik-access.log
      TRAEFIK_LOG_DASHBOARD_ERROR_PATH: /logs/traefik-access.log
      TRAEFIK_LOG_DASHBOARD_AUTH_TOKEN: ${TRAEFIK_LOG_TOKEN}
      TRAEFIK_LOG_DASHBOARD_SYSTEM_MONITORING: true
      TRAEFIK_LOG_DASHBOARD_LOG_FORMAT: json
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5000/api/logs/status",
        ]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

  traefik-log-dashboard:
    image: docker.io/hhftechnology/traefik-log-dashboard:3.1.1@sha256:f982908e6d0665fd361eeef893d50d7743be09e1c95d3a087d4f7d47a651bead
    container_name: traefik-log-dashboard
    restart: unless-stopped
    networks:
      traefik-net:
        ipv4_address: 172.19.0.6
    depends_on:
      traefik-log-dashboard-agent:
        condition: service_healthy
    ports:
      - ${APOLLON_TRAEFIK_LOG_DASHBOARD_PORT}:3000
    environment:
      AGENT_API_URL: http://traefik-log-dashboard-agent:5000
      AGENT_API_TOKEN: ${TRAEFIK_LOG_TOKEN}
      AGENT_NAME: "Traefik Apollon"
      DASHBOARD_MAX_LOGS_DISPLAY: 10000
      SHOW_DEMO_PAGE: false
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: network/traefik-log-dashboard/positions
        target: /data/positions
      - type: volume
        source: docker-data
        volume:
          subpath: network/traefik-log-dashboard/dashboards
        target: /data/dashboards
    labels:
      traefik-conf.port: ${APOLLON_TRAEFIK_LOG_DASHBOARD_PORT}

  authelia:
    image: docker.io/authelia/authelia:4.39.20@sha256:1b363e9279e742397966333f364e0876ae02bf5c876de73e83af6d48c57ff51b
    container_name: authelia
    user: 1000:1000
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: network/authelia/config
        target: /config
      - type: volume
        source: docker-data
        volume:
          subpath: network/authelia/logs
        target: /logs
      - type: volume
        source: docker-data
        volume:
          subpath: network/authelia/secrets
        target: /secrets
    command:
      - authelia
      - --config=/config/configuration.yml
      - --config=/config/oidc.yml
    ports:
      - ${APOLLON_AUTHELIA_PORT}:9091/tcp
    labels:
      traefik-conf.http.routers.authelia-ext.rule: Host(`authelia.${PUBLIC_DOMAIN_NAME}`)
      traefik-conf.http.routers.authelia-ext.service: apollon_authelia
      traefik-conf.http.routers.authelia-ext.entrypoints: https
      traefik-conf.http.routers.authelia-ext.tls.certResolver: tls-resolver
      traefik-conf.http.services.apollon-ext.middlewares: ip-wl@file,geoblock@file
      traefik-conf.port: ${APOLLON_AUTHELIA_PORT}
    environment:
      TZ: Europe/Paris
      X_AUTHELIA_CONFIG_FILTERS: template
    networks:
      traefik-net:
        ipv4_address: 172.19.0.4
    restart: unless-stopped

  traefik-conf:
    container_name: traefik-conf
    restart: unless-stopped
    image: docker.io/mgarnier11/traefik-conf:2.5.0@sha256:86008310e60321df4b8d2442f51341ab75106abb17d4d68ab955346f9109f819
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: network/traefik-conf
        target: /traefik-data
    environment:
      DATA_FILE_PATH: /traefik-data/config.yml
      SERVER_PORT: 3000
      SSH_USER: ${SSH_USER}
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    ports:
      - ${APOLLON_TRAEFIK_CONFIG_PORT}:3000/tcp
    labels:
      traefik-conf.port: ${APOLLON_TRAEFIK_CONFIG_PORT}
    networks:
      traefik-net:
        ipv4_address: 172.19.0.3
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # infrared:
  #   image: ghcr.io/haveachin/infrared:${INFRARED_VERSION}
  #   container_name: infrared
  #   restart: unless-stopped
  #   networks:
  #     traefik-net:
  #       ipv4_address: 172.19.0.4
  #   ports:
  #     - "25565:25565/tcp" # Exposé à l'extérieur via : sudo ufw route allow proto tcp to 172.19.0.4 port 25565
  #     - ${APOLLON_INFRARED_API_PORT}:8080/tcp
  #   labels:
  #     traefik-conf.port: ${APOLLON_INFRARED_API_PORT}
  #   volumes:
  #     - docker-data-infrared:/configs
  # - type: volume
  #   source: docker-data
  #   volume:
  #     subpath: network/infrared
  #   target: /configs
  #   environment:
  #     INFRARED_CONFIG_PATH: "/configs"
  #     INFRARED_API_ENABLED: true
  #     INFRARED_API_BIND: 0.0.0.0:8080

networks:
  traefik-net:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          ip_range: 172.19.0.0/24

volumes:
  docker-data:
    external: true
