name: network
services:
  sablier:
    image: ghcr.io/sablierapp/sablier:1.18.0@sha256:c00c8a01c8c809dd258a8b362ad8ba9a9227753fc9857ae7506fd427175e038c
    container_name: sablier
    restart: unless-stopped
    command:
      - start
      - --provider.name=docker
      - --sessions.default-duration=10m
      - --sessions.expiration-interval=10s
    ports:
      - "${ATHENA_SABLIER_PORT}:10000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: docker-data
        volume:
          subpath: network/sablier
        target: /etc/sablier/themes
    labels:
      traefik-conf.port: ${ATHENA_SABLIER_PORT}

volumes:
  docker-data:
    external: true
