name: network
services:
  sablier:
    image: ghcr.io/sablierapp/sablier:1.13.0@sha256:d53d9250ab4db4fc06df4bb85ee0893664d08b00422ef7d6c46f26865d564d5b
    container_name: sablier
    restart: unless-stopped
    command:
      - start
      - --provider.name=docker
      - --sessions.default-duration=10m
      - --sessions.expiration-interval=10s
    ports:
      - "${ATHENA_SABLIER_PORT}:10000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: docker-data
        volume:
          subpath: network/sablier
        target: /etc/sablier/themes
    labels:
      traefik-conf.port: ${ATHENA_SABLIER_PORT}

volumes:
  docker-data:
    external: true
