name: network
services:
  sablier:
    image: ghcr.io/sablierapp/sablier:1.12.0@sha256:31c6877d69e7d8e627b51343f78234498e8746eb90051deafcfb765caabb584b
    container_name: sablier
    restart: unless-stopped
    command:
      - start
      - --provider.name=docker
      - --sessions.default-duration=10m
      - --sessions.expiration-interval=10s
    ports:
      - "${ATHENA_SABLIER_PORT}:10000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: docker-data
        volume:
          subpath: network/sablier
        target: /etc/sablier/themes
    labels:
      traefik-conf.port: ${ATHENA_SABLIER_PORT}

volumes:
  docker-data:
    external: true
