name: network

services:
  adguard:
    container_name: adguard
    restart: unless-stopped
    image: adguard/adguardhome:${ADGUARD_VERSION}
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: adguard/conf
        target: /opt/adguardhome/conf
      - type: volume
        source: docker-data
        volume:
          subpath: adguard/work
        target: /opt/adguardhome/work
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${ZEPHYR_ADGUARD_PORT}:3000/tcp
    labels:
      traefik-conf.port: ${ZEPHYR_ADGUARD_PORT}
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:3000 || exit 1
      start_period: 10s

  # proxy:
  #   image: mgarnier11/go-proxy:${PROXY_VERSION}
  #   container_name: proxy
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     CONFIG_FILE_PATH: /config/go-config.yml
  #     SERVER_PORT: ${ZEPHYR_PROXY_PORT}
  #     LOG_LEVEL: info
  #     NTFY_SERVER: ${NTFY_SERVER}
  #     NTFY_TOPIC: ${NTFY_TOPIC}
  #     SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
  #   volumes:
  #     - type: volume
  #       source: docker-data
  #       volume:
  #         subpath: proxy
  #       target: /config
  #   labels:
  #     traefik-conf.port: ${ZEPHYR_PROXY_PORT}
  #   healthcheck:
  #     test: wget -q --spider --timeout=5 --tries=1 http://localhost:${ZEPHYR_PROXY_PORT}/ || exit 1
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s

volumes:
  docker-data:
    external: true
