services:
  traefik:
    container_name: traefik
    restart: unless-stopped
    image: mgarnier11/my-traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: docker-data
        volume:
          subpath: traefik/zephyr/certs
        target: /certs
      - type: volume
        source: docker-data
        volume:
          subpath: traefik/zephyr/data
        target: /data
    ports:
      - 80:80/tcp # Exposé à l'extérieur via : sudo ufw route allow proto tcp to 172.19.0.2 port 80
      - 443:443/tcp # Exposé à l'extérieur via : sudo ufw route allow proto tcp to 172.19.0.2 port 443
      - ${APOLLON_TRAEFIK_PORT}:8080/tcp
    labels:
      traefik-conf.port: ${APOLLON_TRAEFIK_PORT}
      traefik-conf.name: traefik.zephyr
    env_file:
      - ./traefik.env
    environment:
      ZEPHYR_IP: ${ZEPHYR_IP}
      APOLLON_IP: ${APOLLON_IP}
      ATHENA_IP: ${ATHENA_IP}
      ATLAS_IP: ${ATLAS_IP}
    command:
      - --configFile=/data/static.yml
      - --ping=true
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:8080/ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  docker-data:
    external: true
