name: observability

services:
  openobserve:
    image: docker.io/openobserve/openobserve:v0.14.4
    container_name: openobserve
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: ${OPENOBSERVE_ROOT_EMAIL}
      ZO_ROOT_USER_PASSWORD: ${OPENOBSERVE_ROOT_PASSWORD}
      ZO_DATA_DIR: /data
      ZO_COMPACT_DATA_RETENTION_DAYS: 30
    ports:
      - ${ATLAS_OPENOBSERVE_PORT}:5080
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: observability/openobserve
        target: /data
    labels:
      traefik-conf.port: ${ATLAS_OPENOBSERVE_PORT}

  vector:
    image: docker.io/timberio/vector:0.42.0-debian
    container_name: vector
    restart: unless-stopped
    user: root:root # required for docker socket access; replace root:root with vector:<docker-gid> for least-privilege
    command: ["--config", "/config/vector.toml"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: docker-data
        volume:
          subpath: observability/vector
        target: /config
    environment:
      HOST_NAME: ${ATLAS_HOSTNAME}
      OPENOBSERVE_HOST: ${ATLAS_IP}
      OPENOBSERVE_PORT: ${ATLAS_OPENOBSERVE_PORT}
      OPENOBSERVE_ROOT_EMAIL: ${OPENOBSERVE_ROOT_EMAIL}
      OPENOBSERVE_ROOT_PASSWORD: ${OPENOBSERVE_ROOT_PASSWORD}
    depends_on:
      - openobserve

volumes:
  docker-data:
    external: true
