name: nextcloud

services:
  nextcloud-db:
    container_name: nextcloud-db
    restart: unless-stopped
    image: mariadb:10.5
    user: 1000:1000
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: nextcloud/db
        target: /var/lib/mysql
      # - type: volume
      #   source: docker-data-nextcloud
      #   volume:
      #     subpath: db
      #   target: /var/lib/mysql
    networks:
      - nextcloud-net
    environment:
      MYSQL_ROOT_PASSWORD: ${NEXTCLOUD_DB_ROOT_PASSWD} # Requested, set the root's password of MySQL service.
      MYSQL_PASSWORD: ${NEXTCLOUD_DB_PASSWD}
      MYSQL_DATABASE: ${NEXTCLOUD_DB_NAME}
      MYSQL_USER: ${NEXTCLOUD_DB_USER}
      MYSQL_LOG_CONSOLE: true

    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m

  nextcloud:
    container_name: nextcloud
    restart: unless-stopped
    image: nextcloud:${NEXTCLOUD_VERSION}
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: nextcloud/data
        target: /data
      - type: volume
        source: docker-data
        volume:
          subpath: nextcloud/config
        target: /var/www/html/config
      # - type: volume
      #   source: docker-data-nextcloud
      #   volume:
      #     subpath: data
      #   target: /data
      # - type: volume
      #   source: docker-data-nextcloud
      #   volume:
      #     subpath: config
      #   target: /var/www/html/config
    networks:
      - nextcloud-net
    ports:
      - ${APOLLON_NEXTCLOUD_PORT}:80
    labels:
      traefik-conf.port: ${APOLLON_NEXTCLOUD_PORT}
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    user: 1000:1000
    depends_on:
      - nextcloud-db
    environment:
      MYSQL_PASSWORD: ${NEXTCLOUD_DB_PASSWD}
      MYSQL_DATABASE: ${NEXTCLOUD_DB_NAME}
      MYSQL_USER: ${NEXTCLOUD_DB_USER}
      MYSQL_HOST: nextcloud-db:3306
      NEXTCLOUD_DATA_DIR: /data
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_URL}
      TRUSTED_PROXIES: 38.242.248.92
      OVERWRITEPROTOCOL: https
      OVERWRITEHOST: ${NEXTCLOUD_URL}
      OVERWRITEWEBROOT: /
      OVERWRITECONDADDR: ^
      OVERWRITECLIURL: https://${NEXTCLOUD_URL}
    healthcheck:
      test: curl -sSf 'http://localhost/status.php' | grep '"installed":true' | grep '"maintenance":false' | grep '"needsDbUpgrade":false' || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  nextcloud-net:

# volumes:
#   docker-data-nextcloud:
#     driver: local
#     driver_opts:
#       type: none
#       device: ${APOLLON_DOCKER_DATA}/nextcloud
#       o: bind

volumes:
  docker-data:
    external: true
