name: trilium

services:
  trilium:
    image: triliumnext/notes:${TRILIUM_VERSION}
    container_name: trilium
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
    ports:
      - ${APOLLON_TRILIUM_PORT}:8080
    volumes:
      - docker-data-trilium:/home/node/trilium-data
    labels:
      traefik-conf.port: ${APOLLON_TRILIUM_PORT}

volumes:
  docker-data-trilium:
    driver: local
    driver_opts:
      type: none
      device: ${APOLLON_DOCKER_DATA}/trilium
      o: bind
