name: wordpress

services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      # - docker-data-wordpress-html:/var/www/html
      - type: volume
        source: docker-data
        volume:
          subpath: wordpress/html
        target: /var/www/html
    ports:
      - ${APOLLON_WORDPRESS_PORT}:80
    labels:
      my-traefik.http.routers.wordpress-admin.rule: Host(`${WORDPRESS_DOMAIN_NAME}`) && (Path(`/wp-admin`)|| Path(`/wp-login.php`))
      my-traefik.http.routers.wordpress-admin.entrypoints: https
      my-traefik.http.routers.wordpress-admin.service: apollon_wordpress
      my-traefik.http.routers.wordpress-admin.middlewares: ip-wl@file
      my-traefik.http.routers.wordpress-admin.tls.certResolver: tls-resolver
      # traefik.http.middlewares.wp-ipwhitelist.ipwhitelist.sourcerange: ${WORDPRESS_ALLOWED_IPS}
      my-traefik.http.routers.wordpress-ext.rule: Host(`${WORDPRESS_DOMAIN_NAME}`)
      my-traefik.http.routers.wordpress-ext.service: apollon_wordpress
      my-traefik.http.routers.wordpress-ext.entrypoints: https
      my-traefik.http.routers.wordpress-ext.tls.certResolver: tls-resolver
      traefik-conf.port: ${APOLLON_WORDPRESS_PORT}
    healthcheck:
      test: curl -f http://localhost || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  wordpress-db:
    image: mysql:5.7
    container_name: wordpress-db
    restart: unless-stopped
    user: 1000:1000
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      # - docker-data-wordpress-db:/var/lib/mysql
      - type: volume
        source: docker-data
        volume:
          subpath: wordpress/db
        target: /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# volumes:
#   docker-data-wordpress-html:
#     driver: local
#     driver_opts:
#       type: none
#       device: ${APOLLON_DOCKER_DATA}/wordpress/html
#       o: bind
#   docker-data-wordpress-db:
#     driver: local
#     driver_opts:
#       type: none
#       device: ${APOLLON_DOCKER_DATA}/wordpress/db
#       o: bind

volumes:
  docker-data:
    external: true
