name: share

services:
  share:
    image: stonith404/pingvin-share:${PINGVIN_SHARE_VERSION}
    restart: unless-stopped
    container_name: share
    ports:
      - ${APOLLON_SHARE_PORT}:3000
    labels:
      my-traefik.http.routers.share-ext.rule: Host(`share.${PUBLIC_DOMAIN_NAME}`)
      my-traefik.http.routers.share-ext.service: apollon_share
      my-traefik.http.routers.share-ext.entrypoints: https
      my-traefik.http.routers.share-ext.tls.certResolver: tls-resolver
      traefik-conf.port: ${APOLLON_SHARE_PORT}
    environment:
      - TRUST_PROXY=true # Set to true if a reverse proxy is in front of the container
    volumes:
      - docker-data-pingvin-data:/opt/app/backend/data
    #   - "./data:/opt/app/backend/data"
    #   - "./data/images:/opt/app/frontend/public/img"

volumes:
  docker-data-pingvin-data:
    driver: local
    driver_opts:
      type: none
      device: ${APOLLON_DOCKER_DATA}/pingvin
      o: bind
