name: share

services:
  share:
    image: stonith404/pingvin-share:${PINGVIN_SHARE_VERSION}
    restart: unless-stopped
    container_name: share
    ports:
      - ${APOLLON_SHARE_PORT}:3000
    labels:
      my-traefik.http.routers.share-ext.rule: Host(`share.${PUBLIC_DOMAIN_NAME}`)
      my-traefik.http.routers.share-ext.service: apollon_share
      my-traefik.http.routers.share-ext.entrypoints: https
      my-traefik.http.routers.share-ext.tls.certResolver: tls-resolver
      my-traefik.http.routers.share-ext.app.middlewares: authelia@file
      # my-traefik.http.routers.share-ext.tls.options: ca-mgarnier11@file
      traefik-conf.port: ${APOLLON_SHARE_PORT}
    environment:
      - TRUST_PROXY=true # Set to true if a reverse proxy is in front of the container
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: pingvin
        target: /opt/app/backend/data

volumes:
  docker-data:
    external: true
