name: utils

services:
  valentine:
    image: mgarnier11/valentine:latest
    container_name: valentine
    restart: unless-stopped
    ports:
      - ${APOLLON_VALENTINE_PORT}:80
    labels:
      traefik-conf.port: ${APOLLON_VALENTINE_PORT}
      traefik-conf.name: aurelie

  share:
    image: stonith404/pingvin-share:${PINGVIN_SHARE_VERSION}
    restart: unless-stopped
    container_name: share
    ports:
      - ${APOLLON_SHARE_PORT}:3000
    labels:
      traefik-conf.port: ${APOLLON_SHARE_PORT}
    environment:
      - TRUST_PROXY=true # Set to true if a reverse proxy is in front of the container
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/pingvin
        target: /opt/app/backend/data

  pdf:
    image: ghcr.io/alam00000/bentopdf:${BENTO_PDF_VERSION}
    container_name: bentopdf
    restart: unless-stopped
    ports:
      - ${APOLLON_BENTO_PDF_PORT}:8080
    labels:
      traefik-conf.port: ${APOLLON_BENTO_PDF_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  trilium:
    image: triliumnext/trilium:${TRILIUM_VERSION}
    container_name: trilium
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      # TRILIUM_OAUTH_BASE_URL: "https://trilium.mgarnier11.fr"
      # TRILIUM_OAUTH_CLIENT_ID: "trilium"
      # TRILIUM_OAUTH_CLIENT_SECRET: "insecure_secret"
      # TRILIUM_OAUTH_ISSUER_BASE_URL: "https://authelia.mgarnier11.fr"
      # TRILIUM_OAUTH_ISSUER_NAME: "Authelia"
      # TRILIUM_OAUTH_ISSUER_ICON: "https://www.authelia.com/images/branding/logo-cropped.png"
    ports:
      - ${APOLLON_TRILIUM_PORT}:8080
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/trilium
        target: /home/node/trilium-data
    labels:
      traefik-conf.port: ${APOLLON_TRILIUM_PORT}

  ntfy:
    image: binwiederhier/ntfy:${NTFY_VERSION}
    container_name: ntfy
    restart: unless-stopped
    command:
      - serve
    environment:
      TZ: ${TIMEZONE}
    ports:
      - ${APOLLON_NTFY_PORT}:80
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/ntfy
        target: /etc/ntfy
    labels:
      traefik-conf.port: ${APOLLON_NTFY_PORT}
      traefik-conf.http.routers.apollon_ntfy.rule: Host(`ntfy.${PUBLIC_DOMAIN_NAME}`)
      traefik-conf.http.routers.apollon_ntfy.middlewares: ip-wl@file,geoblock@file,authelia-basic@file
      traefik-conf.http.routers.apollon_ntfy.entrypoints: https
      traefik-conf.http.routers.apollon_ntfy.tls.certResolver: tls-resolver
      traefik-conf.http.routers.apollon_ntfy.service: apollon_ntfy

    healthcheck:
      test: wget -q --tries=1 http://localhost/v1/health -O - | grep -Eo '\"healthy\":true' || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  docker-data:
    external: true
