name: utils

services:
  valentine:
    image: docker.io/mgarnier11/valentine:latest@sha256:edca091554ab6f67319317de6df1c44f84b47b1e75187caf9b26f1bdcecff11b
    container_name: valentine
    restart: unless-stopped
    ports:
      - ${APOLLON_VALENTINE_PORT}:80
    labels:
      traefik-conf.port: ${APOLLON_VALENTINE_PORT}
      traefik-conf.name: aurelie

  share:
    image: docker.io/stonith404/pingvin-share:v1.13.0@sha256:6bf2bcd3043ee68cb61264f0857511ccf7f212fdb984382b7f2d491635184ad6
    restart: unless-stopped
    container_name: share
    ports:
      - ${APOLLON_SHARE_PORT}:3000
    labels:
      traefik-conf.port: ${APOLLON_SHARE_PORT}
    environment:
      - TRUST_PROXY=true # Set to true if a reverse proxy is in front of the container
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/pingvin
        target: /opt/app/backend/data

  pdf:
    image: ghcr.io/alam00000/bentopdf:2.8.8@sha256:6ef493c8e3bdbaa26c9bfcec330377ae95116fa00660ca0342769063197b1952
    container_name: bentopdf
    restart: unless-stopped
    ports:
      - ${APOLLON_BENTO_PDF_PORT}:8080
    labels:
      traefik-conf.port: ${APOLLON_BENTO_PDF_PORT}
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  trilium:
    image: docker.io/triliumnext/trilium:v0.105.0@sha256:cc6a15edd7ac3df9bb98ad39dd40af8ffda6c1c0bfafe37c26137ddcbecdb7e5
    container_name: trilium
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      # TRILIUM_OAUTH_BASE_URL: "https://trilium.mgarnier11.fr"
      # TRILIUM_OAUTH_CLIENT_ID: "trilium"
      # TRILIUM_OAUTH_CLIENT_SECRET: "insecure_secret"
      # TRILIUM_OAUTH_ISSUER_BASE_URL: "https://authelia.mgarnier11.fr"
      # TRILIUM_OAUTH_ISSUER_NAME: "Authelia"
      # TRILIUM_OAUTH_ISSUER_ICON: "https://www.authelia.com/images/branding/logo-cropped.png"
    ports:
      - ${APOLLON_TRILIUM_PORT}:8080
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/trilium
        target: /home/node/trilium-data
    labels:
      traefik-conf.port: ${APOLLON_TRILIUM_PORT}

  ntfy:
    image: docker.io/binwiederhier/ntfy:v2.28.0@sha256:6ef4b819f722fccdc036af611c4774cfdc2de821ab74fdd48bbf4c9d6f8973da
    container_name: ntfy
    restart: unless-stopped
    command:
      - serve
    environment:
      TZ: ${TIMEZONE}
    ports:
      - ${APOLLON_NTFY_PORT}:80
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/ntfy
        target: /etc/ntfy
    labels:
      traefik-conf.port: ${APOLLON_NTFY_PORT}
      traefik-conf.http.routers.apollon_ntfy.rule: Host(`ntfy.${PUBLIC_DOMAIN_NAME}`)
      traefik-conf.http.routers.apollon_ntfy.middlewares: ip-wl@file,geoblock@file,authelia-basic@file
      traefik-conf.http.routers.apollon_ntfy.entrypoints: https
      traefik-conf.http.routers.apollon_ntfy.tls.certResolver: tls-resolver
      traefik-conf.http.routers.apollon_ntfy.service: apollon_ntfy

    healthcheck:
      test: wget -q --tries=1 http://localhost/v1/health -O - | grep -Eo '\"healthy\":true' || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  docker-data:
    external: true
