name: utils

services:
  valentine:
    image: docker.io/mgarnier11/valentine:latest@sha256:edca091554ab6f67319317de6df1c44f84b47b1e75187caf9b26f1bdcecff11b
    container_name: valentine
    restart: unless-stopped
    ports:
      - ${APOLLON_VALENTINE_PORT}:80
    labels:
      traefik-conf.port: ${APOLLON_VALENTINE_PORT}
      traefik-conf.name: aurelie

  potixx:
    image: docker.io/mgarnier11/potixx:0.0.2@sha256:cb2e05546c31338b572a16299de3899225adb1eeeb3e4c7a3b720e4a5bfd8e03
    container_name: potixx
    restart: unless-stopped
    ports:
      - ${APOLLON_POTIXX_PORT}:8080
    labels:
      traefik-conf.port: ${APOLLON_POTIXX_PORT}
      traefik-conf.http.routers.apollon_potixx_public.rule: Host(`les-potixx.fr`)
      traefik-conf.http.routers.apollon_potixx_public.service: apollon_potixx
      traefik-conf.http.routers.apollon_potixx_public.entrypoints: https
      traefik-conf.http.routers.apollon_potixx_public.tls.certResolver: tls-resolver

  share:
    image: docker.io/stonith404/pingvin-share:v1.13.0@sha256:6bf2bcd3043ee68cb61264f0857511ccf7f212fdb984382b7f2d491635184ad6
    restart: unless-stopped
    container_name: share
    ports:
      - ${APOLLON_SHARE_PORT}:3000
    labels:
      traefik-conf.port: ${APOLLON_SHARE_PORT}
    environment:
      - TRUST_PROXY=true # Set to true if a reverse proxy is in front of the container
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/pingvin
        target: /opt/app/backend/data

  pdf:
    image: ghcr.io/alam00000/bentopdf:2.8.8@sha256:6ef493c8e3bdbaa26c9bfcec330377ae95116fa00660ca0342769063197b1952
    container_name: bentopdf
    restart: unless-stopped
    ports:
      - ${APOLLON_BENTO_PDF_PORT}:8080
    labels:
      traefik-conf.port: ${APOLLON_BENTO_PDF_PORT}
    healthcheck:
      test: wget -q --spider --timeout=5 --tries=1 http://localhost:8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  trilium:
    image: docker.io/triliumnext/trilium:v0.106.0@sha256:be93e82699b12950ac4e2e7b565ce092fe215b8dd6ddfc47921e37b49e6a0e8b
    container_name: trilium
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      # TRILIUM_OAUTH_BASE_URL: "https://trilium.mgarnier11.fr"
      # TRILIUM_OAUTH_CLIENT_ID: "trilium"
      # TRILIUM_OAUTH_CLIENT_SECRET: "insecure_secret"
      # TRILIUM_OAUTH_ISSUER_BASE_URL: "https://authelia.mgarnier11.fr"
      # TRILIUM_OAUTH_ISSUER_NAME: "Authelia"
      # TRILIUM_OAUTH_ISSUER_ICON: "https://www.authelia.com/images/branding/logo-cropped.png"
    ports:
      - ${APOLLON_TRILIUM_PORT}:8080
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/trilium
        target: /home/node/trilium-data
    labels:
      traefik-conf.port: ${APOLLON_TRILIUM_PORT}

  memos:
    image: docker.io/neosmemo/memos:0.31.0@sha256:24c2707ddd8fbd2ceaa7a61ecab86a53cdcde640b24ce572b73da14b00b5785f
    container_name: memos
    restart: unless-stopped
    ports:
      - ${APOLLON_MEMOS_PORT}:5230
    labels:
      traefik-conf.port: ${APOLLON_MEMOS_PORT}
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/memos
        target: /var/opt/memos

  ntfy:
    image: docker.io/binwiederhier/ntfy:v2.29.0@sha256:4c599cf0818965782f93f652bd843e92714992e84d6b88ad17713dc0951cda1f
    container_name: ntfy
    restart: unless-stopped
    command:
      - serve
    environment:
      TZ: ${TIMEZONE}
    ports:
      - ${APOLLON_NTFY_PORT}:80
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/ntfy
        target: /etc/ntfy
    labels:
      traefik-conf.port: ${APOLLON_NTFY_PORT}
      traefik-conf.http.routers.apollon_ntfy.rule: Host(`ntfy.${PUBLIC_DOMAIN_NAME}`)
      traefik-conf.http.routers.apollon_ntfy.middlewares: ip-wl@file,geoblock@file,authelia-basic@file
      traefik-conf.http.routers.apollon_ntfy.entrypoints: https
      traefik-conf.http.routers.apollon_ntfy.tls.certResolver: tls-resolver
      traefik-conf.http.routers.apollon_ntfy.service: apollon_ntfy

    healthcheck:
      test: wget -q --tries=1 http://localhost/v1/health -O - | grep -Eo '\"healthy\":true' || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  docker-data:
    external: true
