name: utils

services:
  postgres:
    image: postgres:18@sha256:8ff36f3c66371cba71d20ceedccfc3de9669a68737607888c4ef0af93abe8e39
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/postgres
        target: /var/lib/postgresql
    ports:
      - ${ATLAS_POSTGRES_PORT}:5432
    labels:
      traefik-conf.port: ${ATLAS_POSTGRES_PORT}

  dbeaver:
    image: dbeaver/cloudbeaver:latest@sha256:33083a988e83c714b98bffc58d45c6c6c15c86816bb446c5f053f1eed66d5247
    container_name: dbeaver
    restart: unless-stopped
    ports:
      - ${ATLAS_DBEAVER_PORT}:8978
    labels:
      traefik-conf.port: ${ATLAS_DBEAVER_PORT}

volumes:
  docker-data:
    external: true
