name: utils

services:
  mysql:
    image: mysql:9.7.1@sha256:8fdf311514c91fa5014e93e98e19d7f5d9eb162a462c13100c956dacc278ee21
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/mysql
        target: /var/lib/mysql
    ports:
      - ${ATLAS_MYSQL_PORT}:3306
    # labels:
    #   traefik-conf.port: ${ATLAS_MYSQL_PORT}

  dbeaver:
    image: dbeaver/cloudbeaver:latest@sha256:a4b7286a88b9b7c05013b624654a7c5997fbbe8f974604a1274a8246cc57c026
    container_name: dbeaver
    restart: unless-stopped
    ports:
      - ${ATLAS_DBEAVER_PORT}:8978
    labels:
      traefik-conf.port: ${ATLAS_DBEAVER_PORT}
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: utils/dbeaver
        target: /opt/cloudbeaver

volumes:
  docker-data:
    external: true
