name: notes

services:
  trilium:
    image: triliumnext/trilium:${TRILIUM_VERSION}
    container_name: trilium
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      # TRILIUM_OAUTH_BASE_URL: "https://trilium.mgarnier11.fr"
      # TRILIUM_OAUTH_CLIENT_ID: "trilium"
      # TRILIUM_OAUTH_CLIENT_SECRET: "insecure_secret"
      # TRILIUM_OAUTH_ISSUER_BASE_URL: "https://authelia.mgarnier11.fr"
      # TRILIUM_OAUTH_ISSUER_NAME: "Authelia"
      # TRILIUM_OAUTH_ISSUER_ICON: "https://www.authelia.com/images/branding/logo-cropped.png"
    ports:
      - ${APOLLON_TRILIUM_PORT}:8080
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: trilium
        target: /home/node/trilium-data
    labels:
      traefik-conf.port: ${APOLLON_TRILIUM_PORT}

  # memos:
  #   image: neosmemo/memos:${MEMOS_VERSION}
  #   container_name: memos
  #   restart: unless-stopped
  #   environment:
  #     - MEMOS_MODE=prod
  #     - MEMOS_PORT=5230
  #   volumes:
  #     - type: volume
  #       source: docker-data
  #       volume:
  #         subpath: memos
  #       target: /var/opt/memos
  #   ports:
  #     - ${APOLLON_MEMOS_PORT}:5230
  #   labels:
  #     traefik-conf.port: ${APOLLON_MEMOS_PORT}

volumes:
  docker-data:
    external: true
