name: beszel

services:
  beszel:
    image: henrygd/beszel:${BESZEL_VERSION}
    container_name: beszel
    restart: unless-stopped
    ports:
      - ${ZEPHYR_BESZEL_PORT}:8090
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: beszel
        target: /beszel_data
    labels:
      traefik-conf.port: ${ZEPHYR_BESZEL_PORT}
    healthcheck:
      # The URL is relative to the container, not the host
      test:
        [
          "CMD",
          "/beszel",
          "health",
          "--url",
          "http://localhost:${ZEPHYR_BESZEL_PORT}",
        ]
      start_period: 10s

  beszel-agent:
    image: henrygd/beszel-agent:${BESZEL_VERSION}
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PORT: ${ZEPHYR_BESZEL_AGENT_PORT}
      KEY: ${BESZEL_AGENT_KEY}
    healthcheck:
      test: ["CMD", "/agent", "health"]
      start_period: 10s

volumes:
  docker-data:
    external: true
