name: stirling-pdf

services:
  stirling-pdf:
    container_name: stirling-pdf
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:${STIRLING_PDF_VERSION}
    ports:
      - ${APOLLON_STIRLING_PDF_PORT}:8080
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
    volumes:
      - type: volume
        source: docker-data
        volume:
          subpath: stirling-pdf/trainingData
        target: /usr/share/tessdata
      - type: volume
        source: docker-data
        volume:
          subpath: stirling-pdf/extraConfigs
        target: /configs
      - type: volume
        source: docker-data
        volume:
          subpath: stirling-pdf/customFiles
        target: /customFiles
      - type: volume
        source: docker-data
        volume:
          subpath: stirling-pdf/logs
        target: /logs
      - type: volume
        source: docker-data
        volume:
          subpath: stirling-pdf/pipeline
        target: /pipeline
    labels:
      traefik-conf.port: ${APOLLON_STIRLING_PDF_PORT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP'",
        ]
      start_period: 10s

volumes:
  docker-data:
    external: true
