name: runner

services:
  runner:
    image: mgarnier11/github-runner:latest
    container_name: github-runner
    restart: unless-stopped
    runtime: sysbox-runc
    environment:
      ACCESS_TOKEN: ${RUNNER_ACCESS_TOKEN}
      RUNNER_SCOPE: org
      ORG_NAME: ${RUNNER_ORG_NAME}
      RUNNER_NAME: runner-apollon
      LABELS: apollon,linux/amd64
      EPHEMERAL: "false"
      DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
      DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME}
      DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD}
      START_DOCKER_SERVICE: "true"
      DEBUG_OUTPUT: "true"
      RUNNER_WORKDIR: "/workdir"
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: "/actions-runner"
      DISABLE_AUTOMATIC_DEREGISTRATION: "true"
    volumes:
      - github-runner-docker-cache:/var/lib/docker
      - github-runner-actions-files:/actions-runner

volumes:
  github-runner-docker-cache:
    external: true
  github-runner-actions-files:
