name: devcontainer

services:
  operis:
    container_name: operis-devcontainer
    restart: unless-stopped
    image: mgarnier11/operis-devcontainer:latest
    runtime: sysbox-runc
    env_file:
      - ./devcontainer.env
    ports:
      - ${ATHENA_OPERISDEVCONTAINER_SSH_PORT}:2222
      - ${ATHENA_OPERISDEVCONTAINER_VSCODE_PORT}:8080
    environment:
      - EXPERT_REGISTRY_TOKEN=${EXPERT_REGISTRY_TOKEN}
      - DEVCONTAINER_ARTIFACTORY_AUTH_TOKEN=${DEVCONTAINER_ARTIFACTORY_AUTH_TOKEN}
      - GIT_EMAIL=${GIT_EMAIL}
      - GIT_NAME=${GIT_NAME}
    secrets:
      - OPERIS_PRIVATE_KEY
    volumes:
      - /ssd-1/operis-devcontainer:/mnt/dev
    labels:
      traefik-conf.port: ${ATHENA_OPERISDEVCONTAINER_VSCODE_PORT}
      traefik-conf.name: operis
      proxy.ports: ${ATHENA_OPERISDEVCONTAINER_SSH_PORT}

  devcontainer:
    container_name: devcontainer
    restart: unless-stopped
    image: mgarnier11/home-container:${HOME_CONTAINER_VERSION}
    runtime: sysbox-runc
    environment:
      - NODE_VERSION=22
      - GIT_EMAIL=${GIT_EMAIL}
      - GIT_NAME=${GIT_NAME}
      - ORCHESTRATOR_API_URL=${ORCHESTRATOR_API_URL}
    ports:
      - ${ATHENA_DEVCONTAINER_SSH_PORT}:2222
      - ${ATHENA_DEVCONTAINER_VSCODE_PORT}:8080
    secrets:
      - SSH_PRIVATE_KEY
    volumes:
      - /ssd-1/devcontainer:/mnt/dev
      - docker-data:/mnt/docker-data
      # - mnt-docker-data-apollon:/mnt/docker-data/apollon
    labels:
      traefik-conf.port: ${ATHENA_DEVCONTAINER_VSCODE_PORT}
      proxy.ports: ${ATHENA_DEVCONTAINER_SSH_PORT}

volumes:
  docker-data:
    external: true

secrets:
  SSH_PRIVATE_KEY:
    environment: "SSH_PRIVATE_KEY"
  OPERIS_PRIVATE_KEY:
    environment: "OPERIS_PRIVATE_KEY"
