name: Deploy stacks
run-name: Deploy stacks ${{ github.event.inputs.stacks_names || 'on push' }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - "autoscaler/**"
      - ".github/**"

  workflow_dispatch:
    inputs:
      stacks_names:
        description: "Stacks to restart"
        required: true

permissions:
  contents: read
  pull-requests: read

jobs:
  redeploy_stack:
    runs-on: linux/arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Get stacks to restart from modified files
        id: get_stacks
        run: |
          set -euo pipefail
          stacks_names=""

          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Stack names provided via workflow_dispatch: ${{ github.event.inputs.stacks_names }}"
            stacks_names="${{ github.event.inputs.stacks_names }}"
          else
            files=$(git diff --name-only --diff-filter=ACMR "${{ github.event.before }}" "${{ github.sha }}")

            # Ignore .github directory
            stacks_names=$(
              echo "$files" \
                | grep '/' \
                | grep -v '^.github/' \
                | cut -d/ -f1 \
                | sort -u \
                | paste -sd,
            )
          fi

          if [ -z "$stacks_names" ]; then
            echo "No stacks to restart."
            exit 1
          fi

          echo "Stacks to restart: $stacks_names"
          echo "STACKS_NAMES=$stacks_names" >> "$GITHUB_OUTPUT"

      - name: Download orchestrator CLI
        run: |
          curl -fL -o ~/orchestrator "https://orchestrator.mgarnier11.fr/cli?arch=arm64&os=linux"
          chmod +x ~/orchestrator

      - name: Restart updated stacks
        env:
          ORCHESTRATOR_MODE: "local"
          ORCHESTRATOR_COMPOSE_DIRECTORY_PATH: ${{ github.workspace }}
          ORCHESTRATOR_S3_ENDPOINT: "https://s3.mgarnier11.fr"
          ORCHESTRATOR_S3_BUCKET: "environment-bucket"
          ORCHESTRATOR_S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          ORCHESTRATOR_S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          ATHENA_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.ATHENA_IP }}"
          ZEPHYR_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.ZEPHYR_IP }}"
          APOLLON_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.APOLLON_IP }}"
          ATLAS_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.ATLAS_IP }}"
        run: |
          set -euo pipefail

          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          cat << 'EOF' > ~/.ssh/ssh_private_key
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          chmod 600 ~/.ssh/ssh_private_key
          cat << 'EOF' > ~/.ssh/config
          Host *
            IdentityFile ~/.ssh/ssh_private_key
            StrictHostKeyChecking no
          EOF

          # get the stacks to restart from the variable set in the previous step
          IFS=',' read -r -a stacks <<< "${{ steps.get_stacks.outputs.STACKS_NAMES }}"
          for stack in "${stacks[@]}"; do
            echo "Restarting stack: $stack"
            ~/orchestrator restart "$stack"
          done
