name: Renovate Merge Redeploy

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  redeploy_stack:
    # if: >-
    #   github.event.pull_request.merged == true &&
    #   startsWith(github.event.pull_request.title, 'chore(deps)') &&
    #   github.event.pull_request.base.ref == 'main'
    runs-on: linux/arm64
    steps:
      - name: Install NFS Client
        run: |
          id -u runner
          id -g runner
          sudo apt-get update
          sudo apt-get install -y nfs-common

      - name: Create mount point and mount NFS share
        run: |
          sudo mkdir -p /mnt/orchestrator
          sudo mount -t nfs -o defaults,vers=3,nolock,comment=cloudconfig \
            ${{ secrets.NFS_SERVER }}:${{ secrets.NFS_PATH }} \
            /mnt/orchestrator

      - name: Check if mount is successful
        run: |
          if mountpoint -q /mnt/orchestrator; then
            echo "NFS share mounted successfully."
            ls -al /mnt/orchestrator
          else
            echo "Failed to mount NFS share."
            exit 1
          fi

      - name: Pull latest changes from NFS share
        run: |
          cd /mnt/orchestrator
          git -c safe.directory=/mnt/orchestrator pull origin main

      - name: Download orchestrator CLI
        run: |
          curl -L -o orchestrator-cli "https://orchestrator.mgarnier11.fr/cli?arch=arm&os=linux"
          chmod +x orchestrator-cli

      # - name: Extract stacks from modified files
      #   id: parse
      #   shell: bash
      #   run: |
      #     set -euo pipefail

      #     # Fetch changed files from PR and filter for stack directories
      #     stacks=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files?per_page=100" | \
      #       jq -r '.[].filename | select(test("^(autoscaler|automation|backup|bitwarden|immich|mealie|media|monitoring|network|paperless|satisfactory|storage|utils)/.+\\.ya?ml$")) | split("/")[0]' | sort -u | tr '\n' ' ' | xargs)

      #     if [[ -z "$stacks" ]]; then
      #       echo "No matching stack files found in PR."
      #       exit 0
      #     fi

      #     echo "Found stacks: $stacks"
      #     echo "stacks=$stacks" >> "$GITHUB_OUTPUT"

      # - name: Restart updated stacks
      #   if: ${{ steps.parse.outputs.stacks != '' }}
      #   run: |
      #     set -euo pipefail
      #     export ORCHESTRATOR_COMPOSE_DIRECTORY=/mnt/orchestrator
      #     for stack in ${{ steps.parse.outputs.stacks }}; do
      #       echo "Restarting stack: $stack"
      #       ./orchestrator-cli restart $stack
      #     done
