name: Renovate Merge Redeploy
run-name: Restart ${{ github.event.pull_request.head.ref }} after merge

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  redeploy_stack:
    # if: >-
    #   github.event.pull_request.merged == true &&
    #   startsWith(github.event.pull_request.title, 'chore(deps)') &&
    #   github.event.pull_request.base.ref == 'main'
    runs-on: linux/arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download orchestrator CLI
        run: |
          curl -L -o orchestrator-cli "https://orchestrator.mgarnier11.fr/cli?arch=arm&os=linux"
          chmod +x orchestrator-cli

      - name: Restart updated stacks
        shell: bash
        env:
          ORCHESTRATOR_MODE: "local"
          ORCHESTRATOR_COMPOSE_DIRECTORY_PATH: ${{ github.workspace }}
          ORCHESTRATOR_S3_ENDPOINT: "https://s3.mgarnier11.fr"
          ORCHESTRATOR_S3_BUCKET: "environment-bucket"
          ORCHESTRATOR_S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          ORCHESTRATOR_S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          ATHENA_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.ATHENA_IP }}"
          ZEPHYR_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.ZEPHYR_IP }}"
          APOLLON_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.APOLLON_IP }}"
          ATLAS_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.ATLAS_IP }}"
        run: |
          set -euo pipefail

          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          cat << 'EOF' > ~/.ssh/ssh_private_key
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          chmod 600 ~/.ssh/ssh_private_key
          cat << 'EOF' > ~/.ssh/config
          Host *
            IdentityFile ~/.ssh/ssh_private_key
            StrictHostKeyChecking no
          EOF

          # get the stack to restart from the name of the branch, which is expected to be renovate/stack-STACK_NAME
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            branch_name="${{ github.event.pull_request.head.ref }}"
            if [[ "$branch_name" =~ ^renovate/stack-(.+)$ ]]; then
              stack_name="${BASH_REMATCH[1]}"
              echo "Found stack name from branch: $stack_name, restarting stack."
              ./orchestrator-cli restart $stack_name
            else
              echo "Branch name does not match expected pattern 'renovate/stack-STACK_NAME'. No stack to restart."
              exit 0
            fi
          else
            echo "This workflow is triggered by a pull request event. No stack to restart."
            exit 0
          fi
