name: Renovate Merge Redeploy
run-name: Restart ${{ github.event.pull_request.head.ref }} after merge

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  redeploy_stack:
    # if: >-
    #   github.event.pull_request.merged == true &&
    #   startsWith(github.event.pull_request.title, 'chore(deps)') &&
    #   github.event.pull_request.base.ref == 'main'
    runs-on: linux/arm64
    steps:
      - name: Install NFS Client
        run: |
          id -u runner
          id -g runner
          sudo apt-get update
          sudo apt-get install -y nfs-common

      - name: Create mount point and mount NFS share
        run: |
          sudo mkdir -p /mnt/orchestrator
          sudo mount -t nfs -o defaults,comment=cloudconfig \
            ${{ secrets.NFS_SERVER }}:${{ secrets.NFS_PATH }} \
            /mnt/orchestrator

      - name: Check if mount is successful
        run: |
          if mountpoint -q /mnt/orchestrator; then
            echo "NFS share mounted successfully."
            ls -al /mnt/orchestrator
          else
            echo "Failed to mount NFS share."
            exit 1
          fi

      - name: Pull latest changes from NFS share
        run: |
          cd /mnt/orchestrator
          git -c safe.directory=/mnt/orchestrator pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main

      - name: Download orchestrator CLI
        run: |
          curl -L -o orchestrator-cli "https://orchestrator.mgarnier11.fr/cli?arch=arm&os=linux"
          chmod +x orchestrator-cli

      - name: Restart updated stacks
        shell: bash
        env:
          ORCHESTRATOR_MODE: "local"
          ORCHESTRATOR_COMPOSE_DIRECTORY_PATH: "/mnt/orchestrator"
          ATHENA_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.ATHENA_IP }}"
          ZEPHYR_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.ZEPHYR_IP }}"
          APOLLON_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.APOLLON_IP }}"
          ATLAS_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.ATLAS_IP }}"
        run: |
          set -euo pipefail

          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          cat << 'EOF' > ~/.ssh/ssh_private_key
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          chmod 600 ~/.ssh/ssh_private_key
          echo "Host *" > ~/.ssh/config
          echo "  IdentityFile ~/.ssh/ssh_private_key" >> ~/.ssh/config

          # get the stack to restart from the name of the branch, which is expected to be renovate/stack-STACK_NAME
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            branch_name="${{ github.event.pull_request.head.ref }}"
            if [[ "$branch_name" =~ ^renovate/stack-(.+)$ ]]; then
              stack_name="${BASH_REMATCH[1]}"
              echo "Found stack name from branch: $stack_name, restarting stack."
              ./orchestrator-cli restart $stack_name
            else
              echo "Branch name does not match expected pattern 'renovate/stack-STACK_NAME'. No stack to restart."
              exit 0
            fi
          else
            echo "This workflow is triggered by a pull request event. No stack to restart."
            exit 0
          fi
